final/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash
from werkzeug.utils import secure_filename
from .models import User, Task,  FinishedTask, Comment, Event
from datetime import datetime
from . import db
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from werkzeug.utils import secure_filename
import uuid as uuid
import os
from website import app

views = Blueprint("views", __name__)


@views.route("/")
def home():
    return render_template("home.html")


@views.route('/register')
def register():
    return render_template("register.html")


@views.route('/login')
def login():
    return render_template('login.html')


@views.route("/dashboard")
@login_required
def dashboard():
    tasks = Task.query.all()
    user = User.query.all()
    finished = FinishedTask.query.all()
    picture = current_user.picture
    tasks_length = len(tasks)
    if tasks_length == 0:
        redirect(url_for('views.dashboard', picture=picture))
    else:
        tasks = Task.query.all()
        user = User.query.all()
        finished = FinishedTask.query.all()
        picture = current_user.picture
        finished_task_length = len(finished)
        alltasks = tasks_length+finished_task_length
        task_percent = int((tasks_length/alltasks)*100)
        finished_percent = int((finished_task_length/alltasks)*100)
        return render_template("dashboard.html", user=user, alltasks=alltasks, tasks=tasks, finished=finished, picture=picture, task_percent=task_percent, finished_percent=finished_percent)
    return render_template("dashboard.html", user=user, tasks=tasks, finished=finished, picture=picture)


@views.route("/profile/<id>", methods=["POST", "GET"])
@login_required
def profile(id):
    profile = User.query.get_or_404(id)
    if request.method == "POST" and current_user:
        profile.username = request.form.get('username')
        profile.first_name = request.form.get('first_name')
        profile.last_name = request.form.get('last_name')
        profile.id = profile.id
        profile.job = request.form.get('job')
        if profile.job == None:
            profile.job = ""
        profile.email = request.form.get('email')
        profile.password = generate_password_hash(
            request.form.get('password'), method="sha256")
        picture = request.files['picture']
        name = secure_filename(picture.filename)
        picture_name = str(uuid.uuid1())+"_"+name
        saved_file = request.files['picture']
        profile.picture = picture_name
        db.session.commit()
        saved_file.save(os.path.join(
            app.config['PROFILE_PICTURE_FOLDER'], picture_name))
        return redirect(url_for('views.profile', user=current_user, id=current_user.id))
    return render_template("profile.html", user=current_user, id=current_user.id)


@views.route("/projects", methods=["GET", "POST"])
@login_required
def project():
    return render_template("projects.html", user=current_user)


@views.route('/tasks', methods=["POST", "GET"])
@login_required
def tasks():
    task = Task.query

    if current_user and request.method == "POST":
        task.open_task = request.form.get("task")
        task.task_descriptif = request.form.get("task_descriptif")
        tasks = Task(open_task=task.open_task, ongoing_task=task.open_task,
                     operator=current_user.id, task_descriptif=task.task_descriptif)
        db.session.add(tasks)
        db.session.commit()
        return redirect('/description/<task_id>"')
    return render_template("tasks.html", user=current_user, tasks=task)


@views.route('/finished/<id>', methods=['POST', "GET"])
@login_required
def finished(id):
    task = Task.query.filter_by(id=id).first()
    finished = FinishedTask.query.filter_by(id=id).first()
    finishedt = FinishedTask(finished_task=task.open_task,
                             finished_task_operator=task.operator, operator_username=task.user.username)
    db.session.add(finishedt)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for("views.dashboard", task=task, finishedt=finished, user=current_user))


@views.route('/update/<id>', methods=["POST", "GET"])
@ login_required
def update(id):
    task = Task.query.get(id)
    if current_user and request.method == "POST":
        task.open_task = request.form["task_to_update"]
        task.ongoing_task = request.form['task_to_update']
        task.task_descriptif = request.form['task_descriptif_to_update']
        db.session.commit()
    return render_template("update.html", task=task, user=current_user)


@views.route('/delete/<id>', methods=["POST", "GET"])
@ login_required
def delete(id):
    task = Task.query.filter_by(id=id).first()
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for("views.dashboard", task=task, user=current_user))


@views.route('/delete_descriptif/<task_descriptif>', methods=["POST", "GET"])
@login_required
def delete_descriptif(task_descriptif):
    task = Task.query.filter_by(task_descriptif=task_descriptif).first()
    if task:
        db.session.delete(task)
        db.session.commit()
        flash("Task deleted successfully.")
    else:
        flash("Task not found.")

    return redirect(url_for('views.dashboard'))


@views.route("/projects/<username>")
@login_required
def projects(username):
    user = User.query.filter_by(username=username).first()
    task = user.task
    finishedtasks = FinishedTask.query.filter_by(
        finished_task_operator=current_user.id).all()
    return render_template("projects.html", user=current_user, task=task, finishedtasks=finishedtasks, username=username)


@views.route("/description/<task_id>", methods=["POST", "GET"])
@login_required
def description(task_id):
    tasks = Task.query.all()
    task = Task.query.filter_by(id=task_id).first()
    text_comment = request.form.get('comment')
    if text_comment is not None:
        comment = Comment(comment=text_comment,
                          operator=current_user.id, task_id=task_id)
        db.session.add(comment)
        db.session.commit()
    comments = Comment.query.all()

    return render_template("description.html", user=current_user, tasks=tasks, task=task,  comments=comments)


@views.route("/update_comment/<comment_id>", methods=["GET", "POST"])
@login_required
def update_comment(comment_id):
    comment = Comment.query.get(comment_id)
    if not comment:
        flash("comment does not exist")

    if comment.operator != current_user.id:
        flash("yout not allowed to modify this Comment")
    if request.method == "POST":
        new_comment = request.form.get("comment")
        comment.comment = new_comment
        db.session.commit()
        flash("Comment updated successfully.")
        return redirect(url_for("views.description", task_id=comment.task_id))
    return render_template("update_comment.html", task_id=comment.task_id)


@ views.route("/delete_comment/<comment_id>", methods=["GET", "POST"])
@ login_required
def delete_comment(comment_id):
    comment = Comment.query.get(comment_id)

    if comment.operator != current_user.id:
        flash("Comment was not deleted")

    if request.method == "POST":
        db.session.delete(comment)
        db.session.commit()
        flash("Comment deleted successfully.")
        return redirect(url_for("views.description", task_id=comment.task_id))
    return render_template("description.html", task_id=comment.task_id, user=current_user)


class SearchForm(FlaskForm):
    searched = StringField("Searched", validators=[DataRequired()])
    submit = SubmitField("Submit")


@ views.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@ views.route("/search_result", methods=["POST"])
@ login_required
def search_result():
    form = SearchForm()
    task = Task.query
    output_searched = form.searched.data
    search_result = task.filter(Task.open_task.like('%'+output_searched+"%"))
    search_result = search_result.order_by(Task.open_task).all()
    return render_template("search_result.html", user=current_user, output=output_searched, form=form, search_result=search_result)


@ views.route("/calendar")
@ login_required
def calendar():
    task = Task.query
    events = Event.query.all()
    return render_template("calendar.html", user=current_user, events=events, task=task)


@app.route('/calendar/add-event', methods=['GET', 'POST'])
def add_event():
    users = User.query.all()
    if request.method == 'POST':
        title = request.form.get('title')
        start_str = request.form.get('start')
        end_str = request.form.get('end')
        url = request.form.get('url')

        if start_str:
            start = datetime.strptime(start_str, '%Y-%m-%d')
        else:
            start = None

        if end_str:
            end = datetime.strptime(end_str, '%Y-%m-%d')
        else:
            end = start

        event = Event(title=title, start=start, end=end, url=url)
        db.session.add(event)
        db.session.commit()
        flash('Event added successfully', category='success')
        return redirect(url_for('views.calendar'))

    return render_template('add_event.html', user=current_user, users=users)


@ app.errorhandler(404)
def error(e):
    return render_template("404.html"), 404


@ app.errorhandler(500)
def internal_error(e):
    return render_template("500.html"), 500

final/website/templates/add_event.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Dashboard</title>
    <link rel="stylesheet" href="{{url_for('static',filename='Css/style.css')}}">
    <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
    <script defer type="text/javascript" src="{{url_for('static',filename='JS/script.js')}}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"
        integrity="sha256-8EcfIJRWyvnu/U0OsfCk05x1JGVmeC2a7sJQHrbWYSA=" crossorigin="anonymous"></script>
</head>

<body>
    <div>
        {% with messages = get_flashed_messages(with_categories=True)%} {%if
        messages%} {%for category, message in messages%} {%if
        category=="error"%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {%else%}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            {{message}}

        </div>
        {%endif%} {%endfor%}
        <script>
            var alerts = document.querySelectorAll('.alert');
            setTimeout(function () {
                alerts.forEach(function (alert) {
                    alert.remove();
                });
            }, 6000);
        </script>
        {%endif%} {%endwith%}
    </div>

    </div>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp"> close </span>
                </div>
            </div>

            <div class="sidebar">
                <a href="/dashboard" class="active">
                    <span class="material-icons-sharp"> dashboard </span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('views.description', task_id=current_user.id)}}">
                    <span class="material-icons-sharp">bar_chart</span>
                    <h3>Projects</h3>
                </a>
                <a href="/calendar">
                    <span class="material-symbols-outlined">
                        calendar_month
                    </span>
                    <h3>Calendar</h3>
                </a>

                <a href="/profile/{{current_user.id}}">
                    <span class="material-icons-sharp">account_circle</span>
                    <h3>Profile</h3>
                </a>

                <a href="/tasks">
                    <span class="material-icons-sharp"> add </span>
                    <h3>New task</h3>
                </a>

                <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
                <a href="/logout"><span class="material-icons-sharp">logout</span>
                    <h3>logout</h3>
                </a>

            </div>
        </aside>

        <main>
            <div class="search-bar">
                <form action="{{url_for('views.search_result')}}" method="POST">
                    <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
                            class="material-icons-sharp">search</span></button>
                </form>
            </div>
            <h1>Dashboard</h1>
            <div class="date">
                <p id="date"></p>
            </div>
            <div class="wide">

                <div class="pip">
                    <div class="fa">
                        <div class="slider2">
                            <form action="{{url_for('add_event')}}" method="POST">
                                <div class="mb-3">
                                    <label for="title">Event title</label>
                                    <input type="text" class="form-control" name="title"
                                        placeholder="Enter the event title">
                                </div>
                                <div class="mb-3">
                                    <label for="start">Start date</label>
                                    <input type="date" class="form-control" name="start"
                                        placeholder="Format is yyyy-mm-ddThh:mm Ignore Thh:mm if you need it for all day">
                                </div>
                                <div class="mb-3">
                                    <label for="end" class="form-label">End date</label>
                                    <input type="date" name="end" class="form-control"
                                        placeholder="leave empty for event to be all day">
                                </div>
                                <div class="mb-3">
                                    <label for="url" class="form-label">Event url</label>
                                    <input type="url" name="url" id="url"
                                        placeholder="Leave empty for no url to be there">
                                </div>

                                <button type="submit" class="btn ">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </main>
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons-sharp"> menu </span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons-sharp active" id='light'> light_mode </span>
                    <span class="material-icons-sharp" id='dark'> dark_mode </span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{current_user.username}}</b></p>

                    </div>
                    {%if user.picture%}
                    <div class="profile-photo">
                        <img class="profile_picture_bar"
                            src='{{url_for("static",filename="/images/profile_pictures/"+user.picture)}}' alt="">
                        {%else%}
                        <span class="material-icons-sharp">account_circle</span>
                    </div>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>


</body>

</html>

<div id="calendar">
</div>

final/website/templates/calendar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Dashboard</title>
    <link rel="stylesheet" href="{{url_for('static',filename='Css/style.css')}}">
    <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
    <script defer type="text/javascript" src="{{url_for('static',filename='JS/script.js')}}"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"
        integrity="sha256-8EcfIJRWyvnu/U0OsfCk05x1JGVmeC2a7sJQHrbWYSA=" crossorigin="anonymous"></script>
</head>

<body>
    <div>
        {% with messages = get_flashed_messages(with_categories=True)%} {%if
        messages%} {%for category, message in messages%} {%if
        category=="error"%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {%else%}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            {{message}}

        </div>
        {%endif%} {%endfor%}
        <script>
            var alerts = document.querySelectorAll('.alert');
            setTimeout(function () {
                alerts.forEach(function (alert) {
                    alert.remove();
                });
            }, 6000);
        </script>
        {%endif%} {%endwith%}
    </div>

    </div>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp"> close </span>
                </div>
            </div>

            <div class="sidebar">
                <a href="/dashboard" class="active">
                    <span class="material-icons-sharp"> dashboard </span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('views.description', task_id=current_user.id)}}">
                    <span class="material-icons-sharp">bar_chart</span>
                    <h3>Projects</h3>
                </a>
                <a href="/calendar">
                    <span class="material-symbols-outlined">
                        calendar_month
                    </span>
                    <h3>Calendar</h3>
                </a>

                <a href="/profile/{{current_user.id}}">
                    <span class="material-icons-sharp">account_circle</span>
                    <h3>Profile</h3>
                </a>

                <a href="/tasks">
                    <span class="material-icons-sharp"> add </span>
                    <h3>New task</h3>
                </a>

                <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
                <a href="/logout"><span class="material-icons-sharp">logout</span>
                    <h3>logout</h3>
                </a>

            </div>
        </aside>

        <main>
            <div class="search-bar">
                {{form.hidden_tag()}}
                <form action="{{url_for('views.search_result')}}" method="POST">
                    <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
                            class="material-icons-sharp">search</span></button>
                </form>
            </div>
            <h1>Dashboard</h1>
            <div class="date">
                <p id="date"></p>
            </div>
            <div class="wide">
                <div id="calendar"></div>
            </div>

        </main>
        <div class="right">
            <div class="top">
                <button id="menu-btn">
                    <span class="material-icons-sharp"> menu </span>
                </button>
                <div class="theme-toggler">
                    <span class="material-icons-sharp active" id='light'> light_mode </span>
                    <span class="material-icons-sharp" id='dark'> dark_mode </span>
                </div>
                <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{current_user.username}}</b></p>

                    </div>
                    {%if user.picture%}
                    <div class="profile-photo">
                        <img class="profile_picture_bar"
                            src='{{url_for("static",filename="/images/profile_pictures/"+user.picture)}}' alt="">
                        {%else%}
                        <span class="material-icons-sharp">account_circle</span>
                    </div>
                    {%endif%}
                </div>
            </div>

            <a href="{{url_for('add_event')}}">
                <button type="button" class="btn-add">Add event</button>
            </a>

        </div>
        <div class="wide">

            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var calendarEl = document.getElementById('calendar');
                    var calendar = new FullCalendar.Calendar(calendarEl, {

                        initialView: 'dayGridMonth',
                        aspectRatio: 2,
                        events: [
                            {% for event in events %}
                        {
                            title: '{{event.title}}',
                            start: '{{event.start}}',
                            end: '{{event.end}}',
                            url: '{{event.url}}',
                        },
                        {% endfor %}
                            {%for t in task %}
                {
                    title: '{{ t.open_task }}',
                        start: '{{ t.date_created }}',
                        },
                {% endfor %}
                        
                    ]
                });
                calendar.updateSize();
                calendar.render();
                });
            </script>

        </div>
    </div>
    </div>
    </div>
    </div>


</body>

</html>

<div id="calendar">
</div>

final/website/templates/completed.html
<div class="income">
    <span class="material-icons-sharp">task_alt</span>
    <div class="middle">
        <div class="left">
            <h2>Completed Tasks</h2>
            {%for f in finished%}
            <h3>finished task: {{f.finished_task}}</h3>
            <h3>author: {{f.operator_username}}</h3>
            {%endfor%}
        </div>
        <div class="progres">
            <svg>
                <circle cx="38" cy="38" r="36" class="prog"></circle>
            </svg>
            <div class="number">
                <p>{{finished_percent}}%</p>
            </div>
        </div>
    </div>
    <small class="text-muted"> Last 24 hours </small>
</div>
<script>
    let progCircle = document.querySelector(".prog");
    let radial = progCircle.r.baseVal.value;
    let circ = radial * 2 * Math.PI;
    progCircle.style.strokeDasharray = circ;
    function setProgress(percent) {
        progCircle.style.strokeDashoffset =
            circ - (percent / 100) * circ;
    }
    setProgress("{{finished_percent}}")
</script>

final/website/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title> Dashboard</title>
  <link rel="stylesheet" href="{{url_for('static',filename='Css/style.css')}}">
  <link rel="shortcut icon" href="{{url_for('static',filename='/images/p.png')}}">
  <script defer type="text/javascript" src="{{url_for('static',filename='JS/script.js')}}"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
</head>

<body>
  <div>
    {% with messages = get_flashed_messages(with_categories=True)%} {%if
    messages%} {%for category, message in messages%} {%if
    category=="error"%}
    <div class="alert alert-danger alert-dismissible " role="alert">
      <div class="message">{{message}}</div>


    </div>
    {%else%}
    <div class="alert alert-primary alert-dismissible " role="alert">
      {{message}}

    </div>
    {%endif%} {%endfor%}
    <script>
      var alerts = document.querySelectorAll('.alert');
      setTimeout(function () {
        alerts.forEach(function (alert) {
          alert.remove();
        });
      }, 6000);
    </script>
    {%endif%} {%endwith%}
  </div>
  <div class="container">
    <aside>
      <div class="top">
        <div class="logo">
          <img src="{{url_for('static',filename='images/logo1.png')}}" alt="Logo" />

        </div>
        <div class="close" id="close-btn">
          <span class="material-icons-sharp"> close </span>
        </div>
      </div>

      <div class="sidebar">
        {%if current_user.username == 'admin' %}
        <a href="/admin/">
          <span class="material-icons-sharp">Admin</span>
          <h3>Admin</h3>
        </a>
        {%endif%}
        <a href="/dashboard" class="active">
          <span class="material-icons-sharp"> dashboard </span>
          <h3>Dashboard</h3>
        </a>
        <a href="{{url_for('views.description', task_id=current_user.id)}}">
          <span class="material-icons-sharp">bar_chart</span>
          <h3>Projects</h3>
        </a>
        <a href="/calendar">
          <span class="material-symbols-outlined">
            calendar_month
          </span>
          <h3>Calendar</h3>
        </a>


        <a href="/profile/{{current_user.id}}">
          <span class="material-icons-sharp">account_circle</span>
          <h3>Profile</h3>
        </a>

        <a href="/tasks">
          <span class="material-icons-sharp"> add </span>
          <h3>New task</h3>
        </a>

        <!-- <span class="material-icons-sharp" a href="/logout"> logout </span> -->
        <a href="/logout"><span class="material-icons-sharp">logout</span>
          <h3>logout</h3>
        </a>

      </div>
    </aside>

    <main>
      <div class="search-bar">
        {{form.hidden_tag()}}
        <form action="{{url_for('views.search_result')}}" method="POST">
          <input type="search" name="searched" placeholder="search for Task"><button type="submit"><span
              class="material-icons-sharp">search</span></button>
        </form>
      </div>
      <h1>Dashboard</h1>

      <div class="date">
        <p id="date"></p>
      </div>
      <br>
      <br>
      <div class="wide">
        <div class="all">
          <div class="slider">
            <img src="{{url_for('static',filename='images/image.png')}}" alt="photo">
            <div class="text">
              <h1>Welcome to ProTask manager</h1>
              <br>
              <p>where you can manage your tasks easily.</p>
            </div>
          </div>
        </div>
        <br>
        <br>
        <div class="insights">
          <!-- open tasks -->
          {%include "open_task.html"%}
          <!-- in progress -->
          {%include "progress.html"%}
          <!-- completed task -->
          {%include "completed.html"%}


        </div>
        <div class="recent-tasks">
          <h2>Recent Tasks</h2>
          <table id="recent-tasks--table">
            <thead>
              <tr>
                <th>User</th>
                <th>Task Name</th>
                <th>Task description </th>
                <th>Date created</th>
              </tr>
            </thead>
            {%for t in tasks%}
            <tr>
              <td><a href="/posts/{{t.user.username}}"
                  style="text-decoration: none; color:black; font-size: 18px; font-weight: bold;">{{t.user.username}}</a>
              </td>
              <td>
                <h4>{{t.open_task}}</h4>
              </td>
              <td> <a href="{{url_for('views.calendar')}}">{{t.task_descriptif}}</a> </td>
              <td>
                <p>{{t.date_created}}</p>
              </td>
            </tr>
            </thead>
            {%endfor%}
          </table>
          <a href="#">Show All</a>
        </div>

    </main>
    <div class="right">
      <div class="top">
        <button id="menu-btn">
          <span class="material-icons-sharp"> menu </span>
        </button>
        <div class="theme-toggler">
          <span class="material-icons-sharp active" id='light'> light_mode </span>
          <span class="material-icons-sharp" id='dark'> dark_mode </span>
        </div>
        <div class="profile">
          <div class="info">
            <p>Hey, <b>{{current_user.username}}</b></p>

          </div>
          <div class="profile-photo">
            {%if picture%}
            <img class="profile_picture_bar" src='{{url_for("static",filename="/images/profile_pictures/"+picture)}}'
              alt="">
            {%else%}
            <span class="material-icons-sharp">account_circle</span>
            {%endif%}
          </div>
        </div>
      </div>

      <div class="recent-updates">
      </div>

    </div>
  </div>
  </div>
  </div>
  </div>
</body>

</html>